// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using biznus_web.Models;

#nullable disable

namespace biznus_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208150803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("biznus_web.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("biznus_web.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("biznus_web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reliable tents for camping and outdoor adventures",
                            IsActive = true,
                            Name = "Tents",
                            Slug = "tents"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Durable backpacks and travel packs",
                            IsActive = true,
                            Name = "Packs",
                            Slug = "packs"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Essential accessories for outdoor activities",
                            IsActive = true,
                            Name = "Accessories",
                            Slug = "accessories"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Perfect gifts for any outdoor enthusiast",
                            IsActive = true,
                            Name = "Gift Cards",
                            Slug = "gift-cards"
                        });
                });

            modelBuilder.Entity("biznus_web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tents",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 8, 2, 790, DateTimeKind.Local).AddTicks(1674),
                            Description = "A reliable tent for your outdoor adventures",
                            ImageUrl = "~/images/patrick-hendry-edguygu93yw-unsplash.jpg",
                            IsAvailable = true,
                            Name = "White Tent",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 8, 2, 790, DateTimeKind.Local).AddTicks(1704),
                            Description = "Keep your drinks hot or cold with this tumbler",
                            ImageUrl = "~/images/ryan-holloway-jydmuaxmib4-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Tin Coffee Tumbler",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Packs",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 8, 2, 790, DateTimeKind.Local).AddTicks(1705),
                            Description = "Durable canvas pack for hiking and travel",
                            ImageUrl = "~/images/denisse-leon-j7cjwufjmg4-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Blue Canvas Pack",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gift Cards",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 8, 2, 790, DateTimeKind.Local).AddTicks(1707),
                            Description = "Perfect gift for any outdoor enthusiast",
                            ImageUrl = "~/images/acme-gift-card.jpg",
                            IsAvailable = true,
                            Name = "Gift Card",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Packs",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 8, 2, 790, DateTimeKind.Local).AddTicks(1709),
                            Description = "Stylish green canvas pack for adventures",
                            ImageUrl = "~/images/jakob-owens-o_bhy3tnsyu-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Green Canvas Pack",
                            Price = 125.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tents",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 8, 2, 790, DateTimeKind.Local).AddTicks(1765),
                            Description = "Spacious family tent for camping",
                            ImageUrl = "~/images/felix-rostig-umv2wr-vbq8-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Red Tent",
                            Price = 250.00m
                        });
                });

            modelBuilder.Entity("biznus_web.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Culture", "Scope");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("biznus_web.Models.CartItem", b =>
                {
                    b.HasOne("biznus_web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("biznus_web.Models.Product", b =>
                {
                    b.HasOne("biznus_web.Models.Category", "CategoryRef")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoryRef");
                });

            modelBuilder.Entity("biznus_web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
