// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using biznus_web.Models;

#nullable disable

namespace biznus_web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("biznus_web.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("biznus_web.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("biznus_web.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Reliable tents for camping and outdoor adventures",
                            IsActive = true,
                            Name = "Tents",
                            Slug = "tents"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Durable backpacks and travel packs",
                            IsActive = true,
                            Name = "Packs",
                            Slug = "packs"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Essential accessories for outdoor activities",
                            IsActive = true,
                            Name = "Accessories",
                            Slug = "accessories"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Perfect gifts for any outdoor enthusiast",
                            IsActive = true,
                            Name = "Gift Cards",
                            Slug = "gift-cards"
                        });
                });

            modelBuilder.Entity("biznus_web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tents",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 39, 19, 632, DateTimeKind.Local).AddTicks(1935),
                            Description = "A reliable tent for your outdoor adventures",
                            ImageUrl = "~/images/patrick-hendry-edguygu93yw-unsplash.jpg",
                            IsAvailable = true,
                            Name = "White Tent",
                            Price = 200.00m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            CategoryId = 3,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 39, 19, 632, DateTimeKind.Local).AddTicks(1965),
                            Description = "Keep your drinks hot or cold with this tumbler",
                            ImageUrl = "~/images/ryan-holloway-jydmuaxmib4-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Tin Coffee Tumbler",
                            Price = 35.00m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Packs",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 39, 19, 632, DateTimeKind.Local).AddTicks(1967),
                            Description = "Durable canvas pack for hiking and travel",
                            ImageUrl = "~/images/denisse-leon-j7cjwufjmg4-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Blue Canvas Pack",
                            Price = 95.00m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Gift Cards",
                            CategoryId = 4,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 39, 19, 632, DateTimeKind.Local).AddTicks(1969),
                            Description = "Perfect gift for any outdoor enthusiast",
                            ImageUrl = "~/images/acme-gift-card.jpg",
                            IsAvailable = true,
                            Name = "Gift Card",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Packs",
                            CategoryId = 2,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 39, 19, 632, DateTimeKind.Local).AddTicks(1971),
                            Description = "Stylish green canvas pack for adventures",
                            ImageUrl = "~/images/jakob-owens-o_bhy3tnsyu-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Green Canvas Pack",
                            Price = 125.00m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tents",
                            CategoryId = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 20, 39, 19, 632, DateTimeKind.Local).AddTicks(1973),
                            Description = "Spacious family tent for camping",
                            ImageUrl = "~/images/felix-rostig-umv2wr-vbq8-unsplash.jpg",
                            IsAvailable = true,
                            Name = "Red Tent",
                            Price = 250.00m
                        });
                });

            modelBuilder.Entity("biznus_web.Models.Translation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Scope")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Culture", "Scope");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Culture = "en-US",
                            Key = "Product_1_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "White Tent"
                        },
                        new
                        {
                            Id = 2,
                            Culture = "ru-RU",
                            Key = "Product_1_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Белая палатка"
                        },
                        new
                        {
                            Id = 3,
                            Culture = "kk-KZ",
                            Key = "Product_1_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Ақ шатыр"
                        },
                        new
                        {
                            Id = 4,
                            Culture = "fr-FR",
                            Key = "Product_1_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Tente blanche"
                        },
                        new
                        {
                            Id = 5,
                            Culture = "en-US",
                            Key = "Product_1_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "A reliable tent for your outdoor adventures"
                        },
                        new
                        {
                            Id = 6,
                            Culture = "ru-RU",
                            Key = "Product_1_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Надёжная палатка для ваших приключений на природе"
                        },
                        new
                        {
                            Id = 7,
                            Culture = "kk-KZ",
                            Key = "Product_1_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Табиғаттағы шытырман оқиғаларға арналған сенімді шатыр"
                        },
                        new
                        {
                            Id = 8,
                            Culture = "fr-FR",
                            Key = "Product_1_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Une tente fiable pour vos aventures en plein air"
                        },
                        new
                        {
                            Id = 9,
                            Culture = "en-US",
                            Key = "Product_2_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Tin Coffee Tumbler"
                        },
                        new
                        {
                            Id = 10,
                            Culture = "ru-RU",
                            Key = "Product_2_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Жестяная кофейная кружка"
                        },
                        new
                        {
                            Id = 11,
                            Culture = "kk-KZ",
                            Key = "Product_2_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Қалайы кофе стаканы"
                        },
                        new
                        {
                            Id = 12,
                            Culture = "fr-FR",
                            Key = "Product_2_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Tasse à café en étain"
                        },
                        new
                        {
                            Id = 13,
                            Culture = "en-US",
                            Key = "Product_2_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Keep your drinks hot or cold with this tumbler"
                        },
                        new
                        {
                            Id = 14,
                            Culture = "ru-RU",
                            Key = "Product_2_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Сохраняйте напитки горячими или холодными с этой кружкой"
                        },
                        new
                        {
                            Id = 15,
                            Culture = "kk-KZ",
                            Key = "Product_2_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Бұл стаканмен сусындарды ыстық немесе суық сақтаңыз"
                        },
                        new
                        {
                            Id = 16,
                            Culture = "fr-FR",
                            Key = "Product_2_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Gardez vos boissons chaudes ou froides avec cette tasse"
                        },
                        new
                        {
                            Id = 17,
                            Culture = "en-US",
                            Key = "Product_3_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Blue Canvas Pack"
                        },
                        new
                        {
                            Id = 18,
                            Culture = "ru-RU",
                            Key = "Product_3_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Синий холщовый рюкзак"
                        },
                        new
                        {
                            Id = 19,
                            Culture = "kk-KZ",
                            Key = "Product_3_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Көк кенеп рюкзак"
                        },
                        new
                        {
                            Id = 20,
                            Culture = "fr-FR",
                            Key = "Product_3_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Sac en toile bleue"
                        },
                        new
                        {
                            Id = 21,
                            Culture = "en-US",
                            Key = "Product_3_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Durable canvas pack for hiking and travel"
                        },
                        new
                        {
                            Id = 22,
                            Culture = "ru-RU",
                            Key = "Product_3_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Прочный холщовый рюкзак для походов и путешествий"
                        },
                        new
                        {
                            Id = 23,
                            Culture = "kk-KZ",
                            Key = "Product_3_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Жүру және саяхат үшін берік кенеп рюкзак"
                        },
                        new
                        {
                            Id = 24,
                            Culture = "fr-FR",
                            Key = "Product_3_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Sac en toile durable pour la randonnée et les voyages"
                        },
                        new
                        {
                            Id = 25,
                            Culture = "en-US",
                            Key = "Product_4_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Gift Card"
                        },
                        new
                        {
                            Id = 26,
                            Culture = "ru-RU",
                            Key = "Product_4_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Подарочная карта"
                        },
                        new
                        {
                            Id = 27,
                            Culture = "kk-KZ",
                            Key = "Product_4_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Сыйлық картасы"
                        },
                        new
                        {
                            Id = 28,
                            Culture = "fr-FR",
                            Key = "Product_4_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Carte cadeau"
                        },
                        new
                        {
                            Id = 29,
                            Culture = "en-US",
                            Key = "Product_4_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Perfect gift for any outdoor enthusiast"
                        },
                        new
                        {
                            Id = 30,
                            Culture = "ru-RU",
                            Key = "Product_4_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Идеальный подарок для любого любителя активного отдыха"
                        },
                        new
                        {
                            Id = 31,
                            Culture = "kk-KZ",
                            Key = "Product_4_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Кез келген табиғат сүйгішіне арналған мінсіз сыйлық"
                        },
                        new
                        {
                            Id = 32,
                            Culture = "fr-FR",
                            Key = "Product_4_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Cadeau parfait pour tout amateur de plein air"
                        },
                        new
                        {
                            Id = 33,
                            Culture = "en-US",
                            Key = "Product_5_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Green Canvas Pack"
                        },
                        new
                        {
                            Id = 34,
                            Culture = "ru-RU",
                            Key = "Product_5_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Зелёный холщовый рюкзак"
                        },
                        new
                        {
                            Id = 35,
                            Culture = "kk-KZ",
                            Key = "Product_5_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Жасыл кенеп рюкзак"
                        },
                        new
                        {
                            Id = 36,
                            Culture = "fr-FR",
                            Key = "Product_5_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Sac en toile verte"
                        },
                        new
                        {
                            Id = 37,
                            Culture = "en-US",
                            Key = "Product_5_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Stylish green canvas pack for adventures"
                        },
                        new
                        {
                            Id = 38,
                            Culture = "ru-RU",
                            Key = "Product_5_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Стильный зелёный холщовый рюкзак для приключений"
                        },
                        new
                        {
                            Id = 39,
                            Culture = "kk-KZ",
                            Key = "Product_5_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Шытырман оқиғаларға арналған стильді жасыл кенеп рюкзак"
                        },
                        new
                        {
                            Id = 40,
                            Culture = "fr-FR",
                            Key = "Product_5_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Sac en toile verte élégant pour les aventures"
                        },
                        new
                        {
                            Id = 41,
                            Culture = "en-US",
                            Key = "Product_6_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Red Tent"
                        },
                        new
                        {
                            Id = 42,
                            Culture = "ru-RU",
                            Key = "Product_6_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Красная палатка"
                        },
                        new
                        {
                            Id = 43,
                            Culture = "kk-KZ",
                            Key = "Product_6_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Қызыл шатыр"
                        },
                        new
                        {
                            Id = 44,
                            Culture = "fr-FR",
                            Key = "Product_6_Name",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Tente rouge"
                        },
                        new
                        {
                            Id = 45,
                            Culture = "en-US",
                            Key = "Product_6_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Spacious family tent for camping"
                        },
                        new
                        {
                            Id = 46,
                            Culture = "ru-RU",
                            Key = "Product_6_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Просторная семейная палатка для кемпинга"
                        },
                        new
                        {
                            Id = 47,
                            Culture = "kk-KZ",
                            Key = "Product_6_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Кемпинг үшін кең отбасылық шатыр"
                        },
                        new
                        {
                            Id = 48,
                            Culture = "fr-FR",
                            Key = "Product_6_Description",
                            Scope = "Product",
                            UpdatedAt = new DateTime(2025, 12, 8, 15, 39, 19, 632, DateTimeKind.Utc).AddTicks(1988),
                            Value = "Tente familiale spacieuse pour le camping"
                        });
                });

            modelBuilder.Entity("biznus_web.Models.CartItem", b =>
                {
                    b.HasOne("biznus_web.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("biznus_web.Models.Product", b =>
                {
                    b.HasOne("biznus_web.Models.Category", "CategoryRef")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoryRef");
                });

            modelBuilder.Entity("biznus_web.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
